"""chartsmith CLI — headless analysis for CI pipelines."""
from __future__ import annotations
import argparse
import asyncio
import contextlib
import difflib
import json
import os
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
import yaml
from pathlib import Path

from src.core.helm_client import (
    ensure_helm_ready,
    repo_add,
    pull_chart,
    render_template as helm_template,
)
from src.core.unwrap import detect_wrapper, unwrap_values
from src.core.manifest_diff import compare_manifests, compute_stats
from src.core.bump_detector import detect_bumps_from_git

EXIT_PASS    = 0
EXIT_BLOCKED = 1
EXIT_ERROR   = 2

_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "safe": 3}
_SEV_EMOJI      = {"critical": "🔴", "high": "🟠", "medium": "🟡", "safe": "🟢"}
_MAX_DIFF_LINES = 120   # cap per-resource diff so a big upgrade stays readable


def _unified_diff(old_yaml: str, new_yaml: str) -> str:
    """Unified diff of two rendered manifests, with the +++/--- header stripped."""
    old_lines = (old_yaml or "").splitlines()
    new_lines = (new_yaml or "").splitlines()
    raw  = difflib.unified_diff(old_lines, new_lines, lineterm="", n=2)
    body = [ln for ln in raw if not ln.startswith(("---", "+++"))]
    if len(body) > _MAX_DIFF_LINES:
        hidden = len(body) - _MAX_DIFF_LINES
        body = body[:_MAX_DIFF_LINES] + [f"... ({hidden} more diff lines truncated)"]
    return "\n".join(body)


_RISK_EMOJI = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}


def _risk_label(stats: dict) -> str:
    if stats["critical"]:
        return "CRITICAL"
    if stats["high"]:
        return "HIGH"
    if stats["medium"]:
        return "MEDIUM"
    return "LOW"


def _blocked(changes: list[dict], fail_on: str) -> bool:
    if fail_on == "none":
        return False
    threshold = _SEVERITY_ORDER.get(fail_on, 99)
    return any(_SEVERITY_ORDER.get(c["severity"], 99) <= threshold for c in changes)


def _format_markdown(
    chart: str,
    from_v: str,
    to_v: str,
    stats: dict,
    changes: list[dict],
    fail_on: str,
) -> str:
    total = stats["total_changes"]
    _r    = _risk_label(stats)
    risk  = f"{_RISK_EMOJI[_r]} {_r}"
    badges = " · ".join(
        f"{_SEV_EMOJI[s]} {stats[s]} {s}"
        for s in ("critical", "high", "medium", "safe")
        if stats[s]
    )

    lines = [
        f"## ChartSmith: `{chart}` · `{from_v}` → `{to_v}`",
        "",
        f"**Risk: {risk}**" + (f" · {badges}" if badges else "") + f" · {total} change(s)",
        "",
    ]

    if total == 0:
        lines.append("✅ No manifest changes detected between these versions.")
        return "\n".join(lines)

    lines += [
        "| # | Severity | Kind | Name | Change |",
        "|---|----------|------|------|--------|",
    ]
    for i, c in enumerate(changes, 1):
        emoji = _SEV_EMOJI.get(c["severity"], "⚪")
        lines.append(
            f"| {i} | {emoji} {c['severity'].upper()} "
            f"| {c['kind']} | `{c['name']}` | {c['change_type']} |"
        )

    detailed = [c for c in changes if c["severity"] in ("critical", "high")]
    if detailed:
        lines += ["", "### Critical & High — diffs", ""]
        for c in detailed:
            emoji = _SEV_EMOJI.get(c["severity"], "")
            lines += [
                "<details>",
                f"<summary>{emoji} <code>{c['kind']}/{c['name']}</code> — "
                f"{c['change_type'].upper()}{(' · ' + c['note']) if c.get('note') else ''}</summary>",
                "",
            ]
            if c.get("action"):
                lines += [f"> ⚡ **Action needed:** {c['action']}", ""]
            diff_text = _unified_diff(c.get("old_yaml", ""), c.get("new_yaml", ""))
            if diff_text:
                lines += ["```diff", diff_text, "```"]
            else:
                lines.append("_(no line-level differences captured)_")
            lines += ["", "</details>", ""]

    lines.append("")
    if fail_on == "none":
        lines.append("ℹ️ **Informational** — no merge gate set (`fail-on: none`).")
    elif _blocked(changes, fail_on):
        lines.append(
            f"⛔ **Blocked** — `{fail_on}`+ severity changes present. "
            "Review required before merging."
        )
    else:
        lines.append(
            f"✅ **Pass** — nothing at `{fail_on}` severity or above."
        )

    lines += ["", "---", "*Generated by [ChartSmith](https://github.com/your-org/chartsmith)*"]
    return "\n".join(lines)


_HTML_DIFF_MAX = 400  # generous on a full page

_SEV_HEX = {"critical": "#FF5C7A", "high": "#FF6B2C", "medium": "#FFC857", "safe": "#3DDC97"}
_CHG_HEX = {"added": "#3DDC97", "removed": "#FF5C7A", "modified": "#A78BFA", "deprecated_api": "#FF6B2C"}


def _html_diff(old_yaml: str, new_yaml: str) -> str:
    import html as _html
    old_lines = (old_yaml or "").splitlines()
    new_lines = (new_yaml or "").splitlines()
    rows, count = [], 0
    for ln in difflib.unified_diff(old_lines, new_lines, lineterm="", n=3):
        if ln.startswith(("---", "+++")):
            continue
        if count >= _HTML_DIFF_MAX:
            rows.append('<div class="dl ctx">… (diff truncated)</div>')
            break
        cls = ("add" if ln.startswith("+") else
               "rem" if ln.startswith("-") else
               "meta" if ln.startswith("@@") else "ctx")
        rows.append(f'<div class="dl {cls}">{_html.escape(ln) or "&nbsp;"}</div>')
        count += 1
    return "".join(rows)


def _format_html(chart, from_v, to_v, stats, changes, fail_on) -> str:
    import html as _html
    esc = _html.escape

    total = stats["total_changes"]
    risk  = _risk_label(stats)
    risk_color = (_SEV_HEX["critical"] if stats["critical"] else
                  _SEV_HEX["high"] if stats["high"] else
                  _SEV_HEX["medium"] if stats["medium"] else _SEV_HEX["safe"])
    blocked = _blocked(changes, fail_on)
    if fail_on == "none":
        verdict = '<span class="verdict info">ℹ️ Informational — no merge gate (fail-on: none)</span>'
    elif blocked:
        verdict = f'<span class="verdict block">⛔ Blocked — {fail_on}+ severity changes present</span>'
    else:
        verdict = f'<span class="verdict pass">✅ Pass — nothing at {fail_on} or above</span>'

    tiles = "".join(
        f'<button class="tile" data-sev="{k}" onclick="toggleFilter(\'{k}\')">'
        f'<div class="tile-label" style="color:{_SEV_HEX[k]}">{k.upper()}</div>'
        f'<div class="tile-num">{stats[k]}</div></button>'
        for k in ("critical", "high", "medium", "safe")
    )

    cards = []
    for c in changes:
        sev = c["severity"]
        scol = _SEV_HEX.get(sev, "#8A93A6")
        ccol = _CHG_HEX.get(c["change_type"], "#8A93A6")
        api = ""
        if c.get("api_version_old") and c.get("api_version_new") and c["api_version_old"] != c["api_version_new"]:
            api = f'<span class="api">{esc(c["api_version_old"])} → {esc(c["api_version_new"])}</span>'
        note = f'<div class="note"><b>Note ·</b> {esc(c["note"])}</div>' if c.get("note") else ""
        action = f'<div class="action"><b>⚡ Action needed ·</b> {esc(c["action"])}</div>' if c.get("action") else ""
        diff_html = _html_diff(c.get("old_yaml", ""), c.get("new_yaml", ""))
        details = (f'<details><summary>▶ Show diff</summary><div class="diff">{diff_html}</div></details>'
                   if diff_html else "")
        ns = (f'<span class="ns"> · ns: {esc(c["namespace"])}</span>'
              if c.get("namespace") and c["namespace"] != "default" else "")
        cards.append(
            f'<div class="card" data-sev="{sev}" style="border-left-color:{scol}">'
            f'<div class="pills">'
            f'<span class="pill" style="color:{scol};border-color:{scol}66">{sev.upper()}</span>'
            f'<span class="pill" style="color:{ccol};border-color:{ccol}66">{esc(c["change_type"])}</span>'
            f'<span class="kind">{esc(c["kind"])}</span>{api}'
            f'</div>'
            f'<div class="cname">{esc(c["name"])}{ns}</div>'
            f'{action}{note}{details}</div>'
        )
    cards_html = "\n".join(cards) or '<div class="empty">No changes detected between these versions.</div>'

    css = """
    :root{--bg:#0E1116;--panel:#161A22;--panelHi:#1C2230;--line:#262C3A;--text:#E6E8EC;--mute:#8A93A6;--ember:#FF6B2C;}
    *{box-sizing:border-box;}
    body{margin:0;background:var(--bg);color:var(--text);font-family:"Inter",ui-sans-serif,system-ui;line-height:1.5;}
    .wrap{max-width:1100px;margin:0 auto;padding:0 32px 80px;}
    header{position:sticky;top:0;background:rgba(14,17,22,.92);backdrop-filter:blur(8px);border-bottom:1px solid var(--line);
      display:flex;align-items:center;justify-content:space-between;padding:16px 32px;z-index:10;}
    .logo{display:flex;align-items:center;gap:10px;font-family:"Space Grotesk",ui-sans-serif,system-ui;font-weight:600;font-size:18px;letter-spacing:-.3px;}
    .logo .em{color:var(--ember);}
    h1{font-family:"Space Grotesk",ui-sans-serif,system-ui;font-size:28px;font-weight:600;letter-spacing:-.5px;margin:32px 0 6px;}
    h1 .arrow{color:var(--ember);}
    .sub{color:var(--mute);font-size:14px;margin-bottom:20px;}
    .verdict{display:inline-block;font-size:13px;font-weight:600;padding:6px 12px;border-radius:8px;margin-bottom:18px;}
    .verdict.pass{background:#3DDC9722;color:#3DDC97;border:1px solid #3DDC9755;}
    .verdict.block{background:#FF5C7A22;color:#FF5C7A;border:1px solid #FF5C7A55;}
    .verdict.info{background:#A78BFA22;color:#A78BFA;border:1px solid #A78BFA55;}
    .tiles{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:8px 0 28px;}
    .tile{background:var(--panelHi);border:1px solid var(--line);border-radius:10px;padding:16px;text-align:left;cursor:pointer;color:var(--text);transition:border-color .15s;}
    .tile:hover{border-color:var(--mute);}
    .tile.active{border-width:1px;box-shadow:0 0 0 1px currentColor inset;}
    .tile-label{font-family:"JetBrains Mono",ui-monospace,monospace;font-size:11px;letter-spacing:.6px;text-transform:uppercase;margin-bottom:6px;}
    .tile-num{font-family:"Space Grotesk",ui-sans-serif,system-ui;font-size:32px;font-weight:600;line-height:1;}
    .card{background:var(--panel);border:1px solid var(--line);border-left:4px solid var(--line);border-radius:12px;padding:14px 18px;margin-bottom:10px;}
    .pills{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-bottom:8px;}
    .pill{font-family:"JetBrains Mono",ui-monospace,monospace;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.4px;padding:3px 8px;border-radius:999px;border:1px solid;}
    .kind{font-family:"JetBrains Mono",ui-monospace,monospace;font-size:11px;color:var(--mute);}
    .api{font-family:"JetBrains Mono",ui-monospace,monospace;font-size:11px;color:var(--ember);}
    .cname{font-family:"Space Grotesk",ui-sans-serif,system-ui;font-size:15px;font-weight:600;}
    .ns{color:var(--mute);font-weight:400;font-size:13px;}
    .note{margin:8px 0;padding:8px 12px;border-radius:6px;background:var(--panelHi);border:1px solid var(--line);font-size:12px;color:var(--mute);}
    .note b{color:var(--ember);}
    .action{margin:8px 0;padding:10px 12px;border-radius:6px;background:#FF6B2C14;border:1px solid #FF6B2C55;font-size:12.5px;color:#FFD2B8;line-height:1.55;}
    .action b{color:var(--ember);}
    details{margin-top:8px;}
    summary{cursor:pointer;color:var(--violet,#A78BFA);font-size:12px;font-weight:600;border:1px solid var(--line);border-radius:6px;padding:4px 10px;display:inline-block;list-style:none;}
    summary::-webkit-details-marker{display:none;}
    .diff{margin-top:10px;font-family:"JetBrains Mono",ui-monospace,monospace;font-size:12px;background:#0D1117;border:1px solid var(--line);border-radius:8px;overflow:auto;max-height:520px;}
    .dl{padding:1px 10px;white-space:pre;}
    .dl.add{background:#1a2d1a;color:#3DDC97;border-left:3px solid #3DDC97;}
    .dl.rem{background:#2d1a1a;color:#FF5C7A;border-left:3px solid #FF5C7A;}
    .dl.meta{background:#1a1a2d;color:#A78BFA;}
    .dl.ctx{color:var(--mute);border-left:3px solid transparent;}
    .empty{padding:32px;text-align:center;color:var(--mute);background:var(--panel);border:1px solid var(--line);border-radius:12px;}
    .foot{color:var(--mute);font-size:12px;margin-top:30px;text-align:center;}
    """

    js = """
    let active=null;
    function toggleFilter(s){
      active = active===s ? null : s;
      document.querySelectorAll('.tile').forEach(t=>{
        const on = t.dataset.sev===active;
        t.classList.toggle('active', on);
        t.style.color = on ? getComputedStyle(t.querySelector('.tile-label')).color : '';
      });
      document.querySelectorAll('.card').forEach(c=>{
        c.style.display = (!active || c.dataset.sev===active) ? '' : 'none';
      });
    }
    """

    logo = ('<svg width="26" height="26" viewBox="0 0 32 32" fill="none">'
            '<path d="M4 22 L16 4 L28 22 L22 22 L16 13 L10 22 Z" stroke="#FF6B2C" stroke-width="2" stroke-linejoin="round"/>'
            '<path d="M10 22 L16 28 L22 22" stroke="#E6E8EC" stroke-width="2" stroke-linejoin="round"/></svg>')

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>ChartSmith · {esc(chart)} {esc(from_v)} → {esc(to_v)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Space+Grotesk:wght@500;600&family=JetBrains+Mono&display=swap" rel="stylesheet">
<style>{css}</style></head>
<body>
<header><div class="logo">{logo}<span>Chart<span class="em">Smith</span></span></div>
<span style="font-size:12px;font-family:'JetBrains Mono',monospace;color:var(--mute)">risk: <b style="color:{risk_color}">{risk}</b></span></header>
<div class="wrap">
  <h1>{esc(chart)} <span style="color:var(--mute)">·</span> {esc(from_v)} <span class="arrow">→</span> {esc(to_v)}</h1>
  <div class="sub">{total} change(s) detected · click a severity tile to filter</div>
  {verdict}
  <div class="tiles">{tiles}</div>
  {cards_html}
  <div class="foot">Generated by ChartSmith</div>
</div>
<script>{js}</script>
</body></html>"""


async def _analyze_one(*, chart, from_version, to_version, values,
                       repo_url=None, repo_name=None, wrapper_key=None):
    """Pull both versions, render, diff. Returns (stats, changes). Raises RuntimeError on failure."""
    await ensure_helm_ready()

    # A short repo name means register it (`helm repo add`) and address as repo/chart;
    # otherwise the repo URL (from a Chart.yaml dependency) is passed straight to pull.
    if repo_name and repo_url:
        await repo_add(repo_name, repo_url)
        repo_url = None

    old_dir = await pull_chart(chart, from_version, repo_url)
    new_dir = await pull_chart(chart, to_version, repo_url)

    values_path = Path(values)
    if not values_path.exists():
        raise RuntimeError(f"Values file not found: {values_path}")
    values_yaml = values_path.read_text()
    user_top = yaml.safe_load(values_yaml) or {}

    wrapper     = wrapper_key or detect_wrapper(user_top, old_dir / "values.yaml")
    values_text = yaml.safe_dump(
        unwrap_values(values_yaml, wrapper), default_flow_style=False, sort_keys=False
    ) if wrapper else values_yaml

    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".yaml", delete=False, dir="/tmp", prefix="chartsmith_"
    )
    tmp.write(values_text); tmp.flush(); tmp.close()
    values_file = Path(tmp.name)
    try:
        old_manifests = await helm_template(old_dir, values_file)
        new_manifests = await helm_template(new_dir, values_file)
    finally:
        values_file.unlink(missing_ok=True)

    for label, manifests in ((from_version, old_manifests), (to_version, new_manifests)):
        if manifests.startswith("# RENDER ERROR"):
            raise RuntimeError(f"helm template failed for {label}:\n{manifests}")

    # Diff engine prints [INFO]/[DEBUG] to stdout — route to stderr to keep stdout clean.
    with contextlib.redirect_stdout(sys.stderr):
        changes = compare_manifests(old_manifests, new_manifests)
    return compute_stats(changes), changes


async def _cmd_analyze(args: argparse.Namespace) -> int:
    try:
        stats, changes = await _analyze_one(
            chart=args.chart, from_version=args.from_version, to_version=args.to_version,
            values=args.values, repo_url=args.repo_url, repo_name=args.repo_name,
            wrapper_key=args.wrapper_key,
        )
    except (RuntimeError, yaml.YAMLError) as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        return EXIT_ERROR

    if args.format == "json":
        print(json.dumps({
            "chart":        args.chart,
            "from_version": args.from_version,
            "to_version":   args.to_version,
            "stats":        stats,
            "changes":      changes,
        }, indent=2))
    elif args.format == "markdown":
        print(_format_markdown(
            args.chart, args.from_version, args.to_version,
            stats, changes, args.fail_on,
        ))
    elif args.format == "html":
        print(_format_html(
            args.chart, args.from_version, args.to_version,
            stats, changes, args.fail_on,
        ))
    else:  # text
        print(f"ChartSmith: {args.chart}  {args.from_version} → {args.to_version}")
        print(f"Changes: {stats['total_changes']}  "
              f"critical={stats['critical']}  high={stats['high']}  "
              f"medium={stats['medium']}  safe={stats['safe']}")
        for c in changes:
            print(f"  [{c['severity'].upper():8}] {c['kind']}/{c['name']} — {c['change_type']}")

    return EXIT_BLOCKED if _blocked(changes, args.fail_on) else EXIT_PASS


# ── CI orchestration (`chartsmith ci`) ───────────────────────────────────────

def _detect_platform() -> str:
    if os.getenv("GITHUB_ACTIONS") == "true":
        return "github"
    if os.getenv("GITLAB_CI") == "true":
        return "gitlab"
    return "local"


def _git(*a: str) -> str:
    return subprocess.run(["git", *a], capture_output=True, text=True).stdout.strip()


def _resolve_refs(args, platform: str) -> tuple[str, str]:
    if args.base_ref:
        return args.base_ref, (args.head_ref or "HEAD")
    if platform == "gitlab":
        base   = os.getenv("CI_MERGE_REQUEST_DIFF_BASE_SHA", "")
        head   = os.getenv("CI_COMMIT_SHA", "HEAD")
        target = os.getenv("CI_MERGE_REQUEST_TARGET_BRANCH_NAME", "")
        if not base and target:
            _git("fetch", "origin", target)
            base = _git("merge-base", f"origin/{target}", "HEAD")
        return (base or "HEAD~1"), head
    if platform == "github":
        head   = os.getenv("GITHUB_SHA", "HEAD")
        target = os.getenv("GITHUB_BASE_REF", "")   # PR target branch
        base = ""
        if target:
            _git("fetch", "origin", target)
            base = _git("merge-base", f"origin/{target}", "HEAD")
        return (base or "HEAD~1"), head
    return "HEAD~1", "HEAD"


def _gitlab_artifact_url(out_path: str) -> str | None:
    proj = os.getenv("CI_PROJECT_PATH")
    job  = os.getenv("CI_JOB_ID")
    if not proj or not job:
        return None
    top, _, rest = proj.partition("/")
    domain = os.getenv("CI_PAGES_DOMAIN", "gitlab.io")
    return f"https://{top}.{domain}/-/{rest}/-/jobs/{job}/artifacts/{out_path}"


def _post_gitlab_comment(body: str) -> bool:
    # Prefer an explicitly API-scoped token; CI_JOB_TOKEN can't post notes.
    token = os.getenv("GITLAB_API_TOKEN") or os.getenv("GITLAB_TOKEN")
    mr    = os.getenv("CI_MERGE_REQUEST_IID")
    proj  = os.getenv("CI_PROJECT_ID")
    api   = os.getenv("CI_API_V4_URL", "https://gitlab.com/api/v4")
    if not (token and mr and proj):
        return False
    base = f"{api}/projects/{proj}/merge_requests/{mr}/notes"
    hdr  = {"PRIVATE-TOKEN": token}
    req  = urllib.request.Request(f"{base}?per_page=100", headers=hdr)
    for note in json.load(urllib.request.urlopen(req, timeout=15)):
        if note["body"].startswith("## ChartSmith"):
            urllib.request.urlopen(urllib.request.Request(
                f"{base}/{note['id']}", method="DELETE", headers=hdr), timeout=15)
    data = urllib.parse.urlencode({"body": body}).encode()
    urllib.request.urlopen(urllib.request.Request(base, data=data, method="POST", headers=hdr), timeout=15)
    return True


def _post_github_comment(body: str) -> bool:
    token = os.getenv("GITHUB_TOKEN")
    repo  = os.getenv("GITHUB_REPOSITORY")
    api   = os.getenv("GITHUB_API_URL", "https://api.github.com")
    ref   = os.getenv("GITHUB_REF", "")
    pr    = ref.split("/")[2] if ref.startswith("refs/pull/") else os.getenv("PR_NUMBER", "")
    if not (token and repo and pr):
        return False
    base = f"{api}/repos/{repo}/issues/{pr}/comments"
    hdr  = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json",
            "User-Agent": "chartsmith"}
    req  = urllib.request.Request(f"{base}?per_page=100", headers=hdr)
    for c in json.load(urllib.request.urlopen(req, timeout=15)):
        if c.get("body", "").startswith("## ChartSmith"):
            urllib.request.urlopen(urllib.request.Request(
                c["url"], method="DELETE", headers=hdr), timeout=15)
    h = dict(hdr); h["Content-Type"] = "application/json"
    data = json.dumps({"body": body}).encode()
    urllib.request.urlopen(urllib.request.Request(base, data=data, method="POST", headers=h), timeout=15)
    return True


async def _cmd_ci(args: argparse.Namespace) -> int:
    platform = _detect_platform()
    base, head = _resolve_refs(args, platform)
    print(f"[ci] platform={platform} base={base} head={head}", file=sys.stderr)

    bumps = detect_bumps_from_git(base_ref=base, head_ref=head, search_path=args.path)
    if not bumps:
        print("No chart version bumps detected — nothing to analyse.")
        return EXIT_PASS

    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    blocked_any = err_any = False
    results = []   # (bump, out_path, stats, changes)

    for b in bumps:
        src_dir = os.path.dirname(b.get("source_file", ""))
        values  = os.path.join(src_dir, args.values_file) if src_dir else args.values_file
        print(f"==> {b['chart']} {b['from_version']} -> {b['to_version']} (values: {values})")
        if not os.path.exists(values):
            print(f"   [skip] no values file at {values}")
            continue
        try:
            stats, changes = await _analyze_one(
                chart=b["chart"], from_version=b["from_version"], to_version=b["to_version"],
                values=values, repo_url=b.get("repo_url"), repo_name=b.get("repo_name"),
                wrapper_key=b.get("wrapper_key"),
            )
        except (RuntimeError, yaml.YAMLError) as e:
            print(f"   [error] {e}", file=sys.stderr)
            err_any = True
            continue

        html = _format_html(b["chart"], b["from_version"], b["to_version"], stats, changes, args.fail_on)
        out  = outdir / f"chartsmith-{b['chart'].replace('/', '-')}.html"
        out.write_text(html)
        results.append((b, out, stats, changes))
        if _blocked(changes, args.fail_on):
            blocked_any = True
        print(f"   critical={stats['critical']} high={stats['high']} "
              f"medium={stats['medium']} safe={stats['safe']} -> {out}")

    # ── always surface report locations in the job log ───────────────────────
    if results:
        print("\nReports:")
        for b, out, stats, _ in results:
            url = _gitlab_artifact_url(str(out)) if platform == "gitlab" else None
            loc = url or str(out)
            print(f"  • {b['chart']} {b['from_version']} → {b['to_version']} "
                  f"(risk {_risk_label(stats)}) — {loc}")

    # ── publish comment (best-effort; never fail the job on a comment error) ──
    if results and not args.no_comment:
        try:
            if platform == "gitlab":
                lines = []
                for b, out, stats, _ in results:
                    url   = _gitlab_artifact_url(str(out))
                    label = f"{b['chart']} `{b['from_version']} → {b['to_version']}` · risk {_risk_label(stats)}"
                    lines.append(f"- **{label}** — [📊 Open report]({url})" if url else f"- **{label}**")
                body = "## ChartSmith\n\nRendered upgrade analysis (opens in a new tab):\n\n" + "\n".join(lines)
                print("\n📝 Posted ChartSmith links to MR." if _post_gitlab_comment(body)
                      else "\n[info] GITLAB_TOKEN/MR context missing — comment skipped (links above).")
            elif platform == "github":
                # GitHub renders markdown comments richly — post the full report inline.
                parts = [_format_markdown(b["chart"], b["from_version"], b["to_version"], stats, changes, args.fail_on)
                         for b, _, stats, changes in results]
                body = "## ChartSmith\n\n" + "\n\n---\n\n".join(parts)
                print("\n📝 Posted ChartSmith report to PR." if _post_github_comment(body)
                      else "\n[info] GITHUB_TOKEN/PR context missing — comment skipped (reports above).")
        except Exception as e:
            print(f"\n[warn] comment posting failed ({e}) — report links are listed above.", file=sys.stderr)

    return EXIT_BLOCKED if blocked_any else (EXIT_ERROR if err_any else EXIT_PASS)


def _cmd_detect_bump(args: argparse.Namespace) -> int:
    bumps = detect_bumps_from_git(
        base_ref=args.base_ref,
        head_ref=args.head_ref,
        search_path=args.path,
    )

    if args.format == "env":
        if not bumps:
            print("CHARTSMITH_BUMPS_FOUND=false")
        else:
            b = bumps[0]
            print("CHARTSMITH_BUMPS_FOUND=true")
            print(f"CHARTSMITH_CHART={b['chart']}")
            print(f"CHARTSMITH_FROM={b['from_version']}")
            print(f"CHARTSMITH_TO={b['to_version']}")
            if b.get("repo_name"):
                print(f"CHARTSMITH_REPO_NAME={b['repo_name']}")
            if b.get("repo_url"):
                print(f"CHARTSMITH_REPO_URL={b['repo_url']}")
            if b.get("wrapper_key"):
                print(f"CHARTSMITH_WRAPPER_KEY={b['wrapper_key']}")
    else:
        print(json.dumps(bumps, indent=2))

    return EXIT_PASS


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="chartsmith",
        description="Helm upgrade advisor — forecast breaking changes before you upgrade.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # ── analyze ──────────────────────────────────────────────────────────────
    a = sub.add_parser("analyze", help="Diff two chart versions against your values.yaml")
    a.add_argument("--chart",        required=True,
                   help="Chart name, e.g. grafana-community/loki")
    a.add_argument("--from-version", required=True, dest="from_version")
    a.add_argument("--to-version",   required=True, dest="to_version")
    a.add_argument("--values",       required=True,
                   help="Path to your values.yaml (or - for stdin)")
    a.add_argument("--repo-name",    dest="repo_name", default=None,
                   help="Helm repo short name (added via helm repo add)")
    a.add_argument("--repo-url",     dest="repo_url", default=None,
                   help="Helm repo URL")
    a.add_argument("--context",      default="plain",
                   choices=["plain", "argocd", "umbrella", "helmfile"])
    a.add_argument("--wrapper-key",  dest="wrapper_key", default=None,
                   help="ArgoCD/umbrella wrapper key (auto-detected if omitted)")
    a.add_argument("--fail-on",      dest="fail_on", default="critical",
                   choices=["none", "critical", "high", "medium", "safe"],
                   help="Exit 1 when changes at this severity or above are found")
    a.add_argument("--format",       default="markdown",
                   choices=["markdown", "json", "text", "html"])

    # ── detect-bump ──────────────────────────────────────────────────────────
    d = sub.add_parser(
        "detect-bump",
        help="Detect Helm chart version bumps in a git diff (Chart.yaml, ArgoCD, helmfile)",
    )
    d.add_argument("--base-ref", required=True, dest="base_ref",
                   help="Base git ref (e.g. $CI_MERGE_REQUEST_DIFF_BASE_SHA)")
    d.add_argument("--head-ref", default="HEAD", dest="head_ref",
                   help="Head git ref (default: HEAD)")
    d.add_argument("--path",     default=".",
                   help="Directory to search within (default: .)")
    d.add_argument("--format",   default="json", choices=["json", "env"],
                   help="json = structured list; env = shell-sourceable KEY=VALUE")

    # ── ci ────────────────────────────────────────────────────────────────────
    c = sub.add_parser(
        "ci",
        help="One-shot CI driver: detect bumps in the MR/PR, analyse each, write HTML "
             "reports, and post a comment. Auto-detects GitLab or GitHub from env.",
    )
    c.add_argument("--output-dir",  dest="output_dir", default="reports",
                   help="Where to write HTML reports (publish as CI artifacts)")
    c.add_argument("--values-file", dest="values_file", default="values.yaml",
                   help="Values filename next to each changed Chart.yaml")
    c.add_argument("--fail-on",     dest="fail_on", default="none",
                   choices=["none", "critical", "high", "medium", "safe"],
                   help="Exit 1 when changes at this severity or above are found")
    c.add_argument("--path",        default=".", help="Directory to search for bumps")
    c.add_argument("--base-ref",    dest="base_ref", default=None,
                   help="Override base ref (else derived from CI env)")
    c.add_argument("--head-ref",    dest="head_ref", default=None,
                   help="Override head ref (else derived from CI env)")
    c.add_argument("--no-comment",  dest="no_comment", action="store_true",
                   help="Generate reports but don't post an MR/PR comment")

    return parser


def main():
    parser = _build_parser()
    args   = parser.parse_args()

    if args.command == "analyze":
        sys.exit(asyncio.run(_cmd_analyze(args)))
    elif args.command == "detect-bump":
        sys.exit(_cmd_detect_bump(args))
    elif args.command == "ci":
        sys.exit(asyncio.run(_cmd_ci(args)))


if __name__ == "__main__":
    main()
